name: sonar-check

on:
  push:
    branches:
      - master

jobs:
  sonar-scanner-run:
    if: github.repository == 'madrave/route-point'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v3

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.branch.name=${GITHUB_REF#refs/heads/} \
            -Dproject.settings=sonar-project.properties
